from typing import Protocol, Optional, Any


class ICache(Protocol):
    async def get(self, key: str) -> Optional[str]: ...
    async def set(self, key: str, value: Any, expire_ms: int = None) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def get_json(self, key: str) -> dict | None: ...
    async def set_json(self, key: str, data: dict, expire_ms: int = None) -> None: ...
