import uuid
from typing import Protocol

from apps.common.dao.device import DeviceDomain, DeviceIn
from apps.common.dao.user import (
    CreateUser,
    PandoraCredDomain,
    PandoraCredIn,
    UserDomain,
)


class IUserRepo(Protocol):
    async def get_by_email(self, email: str) -> UserDomain | None: ...
    async def create(self, user_in: CreateUser) -> UserDomain: ...
    async def get(self, user_id: int) -> UserDomain: ...
    async def delete(self, user_id: int) -> None: ...
    async def upsert_credentials(self, pandora_cred: PandoraCredIn) -> None: ...
    async def get_credentials(self, user_id: int) -> PandoraCredDomain: ...


class IDeviceRepo(Protocol):
    async def get_all_devices(self, user_id: int) -> list[DeviceDomain]: ...
    async def pair_device(self, device: DeviceIn) -> DeviceDomain: ...
    async def upsert_device(self, device: DeviceIn) -> DeviceDomain: ...
    async def get_by_name(self, device_name: str) -> DeviceDomain | None: ...
    async def delete_device(self, device_id: uuid.UUID): ...
