from typing import Protocol

from apps.common.dao.user import (
    UserDomain,
    PandoraCredIn,
    PandoraCredDomain,
    CreateUser,
)


class IUserRepo(Protocol):
    async def get_by_email(self, email: str) -> UserDomain | None: ...
    async def create(self, user_in: CreateUser) -> UserDomain: ...
    async def get(self, user_id: int) -> UserDomain: ...
    async def delete(self, user_id: int) -> None: ...
    async def upsert_credentials(self, pandora_cred: PandoraCredIn) -> None: ...
    async def get_credentials(self, user_id: int) -> PandoraCredDomain: ...
