import uuid
from typing import Protocol

from apps.common.const import ServiceName
from apps.common.dao.config import ConfigIn
from apps.common.dao.device import DeviceDomain, DeviceIn, DeviceUpdate
from apps.common.dao.user import (
    CreateUser,
    UserDomain,
)
from apps.common.infrastructure.database.models import Credential


class IUserRepo(Protocol):
    async def get_by_email(self, email: str) -> UserDomain | None: ...
    async def create(self, user_in: CreateUser) -> UserDomain: ...
    async def get(self, user_id: int) -> UserDomain: ...
    async def delete(self, user_id: int) -> None: ...


class IConfigRepo(Protocol):
    async def upsert_config(self, config: ConfigIn) -> Credential | None: ...
    async def get_config(self, user_id: int, service: ServiceName | str) -> Credential | None: ...

class IDeviceRepo(Protocol):
    async def get_all_devices(self, user_id: int) -> list[DeviceDomain]: ...
    async def pair_device(self, device: DeviceIn) -> DeviceDomain: ...
    async def upsert_device(self, device: DeviceIn) -> DeviceDomain: ...
    async def update_device(self, device_update: DeviceUpdate) -> DeviceDomain: ...
    async def get_by_name(self, device_name: str) -> DeviceDomain | None: ...
    async def delete_device(self, device_id: uuid.UUID): ...
    async def get(self, device_id: uuid.UUID) -> DeviceDomain: ...
